# Generated by Django 4.1.2 on 2023-03-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_category_id_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
