# Generated by Django 4.1.2 on 2023-03-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
