# Generated by Django 4.1.2 on 2023-06-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_orderitem_cart'),
        ('post', '0011_orderitem_session_key'),
    ]

    operations = [
    ]
