# Generated by Django 4.1.2 on 2022-11-08 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                max_length=25,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_password",
                        message="Password must have a lowercase letter, a uppercase letter, a special character and must be 8-25 characters long",
                        regex="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%)])",
                    ),
                    django.core.validators.MinLengthValidator(7),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=25,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username must start with a letter and must be 4-25 characters long",
                        regex="^[a-zA-Z][a-zA-Z0-9_]{3,24}$",
                    ),
                    django.core.validators.MinLengthValidator(4),
                ],
            ),
        ),
    ]
