# Generated by Django 4.1.2 on 2022-11-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_password"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="is_Premium",),
    ]
