# Generated by Django 4.1.2 on 2022-11-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser", old_name="status", new_name="roles",
        ),
    ]
